In [22]:
f = open('sentences.txt', 'r')
lines = []
for line in f:
    lines.append(line.lower())

In [25]:
len(lines)
print lines

['in comparison to dogs, cats have not undergone major changes during the domestication process.\n', 'as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.\n', 'a common interactive use of cat for a single file is to output the content of a file to standard output.\n', 'cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.\n', 'in one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.\n', 'the domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.\n', 'domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).\n', 'however, if the output is piped or redirected, cat is unnecessary.\n', 'cat with one named file is safer where human

In [36]:
import re

tokens = []
for line in lines:
    new_line = re.split('[^a-z]', line)
    new_line = [word for word in new_line if len(word) > 0]
    tokens.append(new_line)
print tokens

[['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process'], ['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes'], ['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output'], ['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals'], ['in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin'], ['the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organism

In [60]:
token_dict = {}
for token_line in tokens:
    for token in token_line:
        if token_dict.get(token) == None:
            token_dict[token] = 1
        else:
            token_dict[token] = token_dict[token] + 1
            
print len(token_dict.keys())
keys = token_dict.keys()

254


In [61]:
import numpy
matrix = numpy.zeros((len(lines), len(keys)))

In [65]:
for idx_col, val_col in enumerate(keys):
    for idx_row, val_row in enumerate(tokens):
        matrix[idx_row, idx_col] = val_row.count(val_col)

print matrix

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 2. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [104]:
from scipy.spatial import distance

distances = []

for i in range(matrix.shape[0]):
    distances.append(distance.cosine(matrix[0], matrix[i]))

In [105]:
distances_copy = list(distances)
distances_copy.sort()
for min_value in distances_copy[0:3]:
    print distances.index(min_value)


0
6
4
