In [8]:
import numpy

c = numpy.array([False, False, True])

f = numpy.arange(1, 2, 0.3, dtype=float)

b = numpy.array([1, 2, 3, 4, 5], dtype=float)

print type(c)
print type(f)
print type(b)

<type 'numpy.ndarray'>
<type 'numpy.ndarray'>
<type 'numpy.ndarray'>


In [9]:
a = numpy.array([6, 3, -5])
b = numpy.array([-1, 0, 7])

In [30]:
 a = numpy.array([8, 10, -1, 0, 0])
#a = a.reshape((1, 5))

a = a[:, numpy.newaxis]

#a = a.reshape((5, 1))

#a = a[numpy.newaxis, :]

print a

[[ 8]
 [10]
 [-1]
 [ 0]
 [ 0]]


In [33]:
a = numpy.eye(4, 5)
print a    
print a[[0, 3], [1, 3]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
[1. 1.]


In [37]:
a = numpy.eye(4, 4)

#print numpy.inv(a)

#print numpy.det(a)

print numpy.linalg.det(a)

print numpy.linalg.inv(a)

1.0
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [47]:
print numpy.linalg.matrix_rank(a)

#print numpy.eig(a)

print numpy.linalg.eig(a)

#print numpy.solve(a)

#print numpy.linalg.solve(a)

4
(array([1., 1., 1., 1.]), array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]))


In [50]:
print numpy.arange(1, 13, 2).reshape((3, 2))

print numpy.ones((10, 10))

#print numpy.array([4, 3, 2], [2, 9, 1], [3, 1, 9])

#print numpy.eye((4, 5))

print numpy.eye(2, 3)

[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]]
